init -1:
    define cat = Character("Кот")
    define hero = Character("Мэллори")
    define suicide = Character("suicide")
    define pharmacist = Character("Амелинда")
    define unknown = Character("Unknown")
    define artist = Character("Artist")
    define lady_mask = Character("Masked Lady")
    define passer = Character("Passer")
    define iso = Character("iso")
    define darklady = Character("Мисс Дарк")
