init -1:
    define cat = Character("Кот")
    define hero = Character("Мэллори")
    define suicide = Character("Клод")
    define pharmacist = Character("Амелинда")
    define unknown = Character("Unknown")
    define artist = Character("Художник")
    define passer = Character("Passer")
    define iso = Character("iso")
    define darklady = Character("Мисс Д’Арк")
    define vivi = Character("Вивиен")
    define nelly = Character("Нелли")
    define rogue = Character("Бандит")
    define poor = Character("Нищий")
