define cat = Character("Cat")
define hero = Character("Main Hero")
define suicide = Character("suicide")
define pharmacist = Character("Pharmacist")
define unknown = Character("Unknown")
define artist = Character("Artist")
define lady_mask = Character("Masked Lady")
define passer = Character("Passer")
